# Generated by Django 4.0.6 on 2022-07-18 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Category_blog',
                'verbose_name_plural': 'Categories_blog',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Kurs nomi')),
                ('count_module', models.IntegerField(verbose_name='Modullar soni')),
                ('image', models.ImageField(upload_to='course_img/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('img', models.ImageField(upload_to='blog_img/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Blog')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('like', models.IntegerField(default=0, verbose_name='Like')),
                ('dislike', models.IntegerField(default=0, verbose_name='Dislike')),
                ('popular', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('category_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
